# Generated by Django 3.2.6 on 2021-09-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RollinApp', '0002_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='victory',
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(blank=True, max_length=50, null=True)),
                ('team2', models.CharField(blank=True, max_length=50, null=True)),
                ('victory', models.CharField(blank=True, max_length=50, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RollinApp.match')),
            ],
        ),
    ]
