# Generated by Django 3.2.6 on 2021-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollinApp', '0003_auto_20210903_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchdetail',
            name='matchid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
