# Generated by Django 3.2.6 on 2021-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollinApp', '0004_auto_20210903_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
